# Generated by Django 4.0 on 2022-01-18 22:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to=accounts.models.custom_upload_to),
        ),
    ]
